In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [17]:
from sklearn.datasets import make_classification

In [18]:
### create a dataset

x,y=make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=20 )

In [19]:
x

array([[-0.77228288,  0.19670614,  1.64949844, ...,  0.11495344,
         0.75403833,  1.31646629],
       [ 1.46611492, -0.56998489, -0.49092075, ..., -0.43100156,
         1.05412151, -1.37878943],
       [ 0.26515873,  2.354382  , -1.30263989, ..., -0.0789764 ,
        -0.08921751, -1.29899056],
       ...,
       [ 0.10999623,  0.15559844,  0.6135063 , ..., -0.24700341,
        -0.54999422,  0.96164937],
       [ 0.36974471,  0.89851877, -1.65166284, ...,  0.42067259,
        -0.03992643,  1.37658315],
       [ 0.3600093 ,  1.03649588, -0.24432422, ..., -0.13441277,
         0.0543356 , -1.280987  ]])

In [20]:
y

array([1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0])

In [21]:
pd.DataFrame(x)

,0,1,2,3,4,5,6,7,8,9
0,-0.772283,0.196706,1.649498,0.471559,0.322462,-0.143971,-0.873637,0.114953,0.754038,1.316466
1,1.466115,-0.569985,-0.490921,-1.170983,1.278384,-0.720606,0.680824,-0.431002,1.054122,-1.378789
2,0.265159,2.354382,-1.302640,0.283290,-0.497433,-1.736997,0.888013,-0.078976,-0.089218,-1.298991
3,1.054882,0.830666,0.012437,-0.435215,-1.780593,1.953013,-1.237963,0.662300,-0.005446,2.381620
4,-0.806635,-0.780728,1.227786,-0.195062,-0.624200,1.051022,-0.099346,0.160575,-0.496138,0.302153
...,...,...,...,...,...,...,...,...,...,...
995,-0.894265,-1.605784,-0.095059,1.710907,1.303194,0.323110,-0.830412,-0.113191,-1.453720,1.021412
996,-0.015521,-0.916188,0.786272,-0.120857,2.091906,0.031402,-0.674116,-0.322670,0.076854,0.590644
997,0.109996,0.155598,0.613506,0.031932,1.957641,0.346085,-0.887701,-0.247003,-0.549994,0.961649
998,0.369745,0.898519,-1.651663,0.554387,-1.226184,-1.243076,-0.687002,0.420673,-0.039926,1.376583
999,0.360009,1.036496,-0.244324,-1.291718,-0.196403,-0.208046,0.833086,-0.134413,0.054336,-1.280987

In [22]:
pd.DataFrame(y)

     0
0    1
1    1
2    0
3    0
4    1
..  ..
995  1
996  1
997  1
998  0
999  0

[1000 rows x 1 columns]

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30, random_state=20)

In [25]:
x_train

array([[ 0.63729448,  1.74886758,  0.47054755, ..., -0.20495553,
        -0.35257907, -0.62506851],
       [-0.64972066, -0.47664915,  1.72524183, ...,  0.010238  ,
        -0.89026184,  1.06113844],
       [-0.77084933, -0.98006728, -0.77971027, ..., -0.33907431,
         0.68073197, -0.94663953],
       ...,
       [-0.79930536,  0.11781555,  0.20815763, ...,  0.25747688,
         0.16624095, -0.72144823],
       [-1.36527788,  1.01838357, -1.41290922, ..., -0.31790712,
         2.164455  , -1.39429993],
       [-1.16123782,  1.11488685,  0.33140284, ..., -0.26218233,
         0.82088279,  0.43544656]])

In [26]:
x_test

array([[-0.35764704,  0.76350621,  1.34763384, ...,  0.09569857,
        -0.2201177 , -0.84016591],
       [-0.79072695, -0.67684259,  0.00908578, ...,  0.46120524,
         0.35496047,  1.45060919],
       [-0.24568811, -1.09200888,  1.03254717, ..., -0.31349402,
        -0.57178771, -0.85220079],
       ...,
       [-0.22297781, -0.03330364, -0.09935947, ..., -0.38474147,
        -0.12149634, -1.29266957],
       [ 0.29907192, -0.56833106,  0.08066192, ..., -0.77845744,
        -0.8582511 , -2.78266852],
       [ 0.50136178, -0.87181653,  0.55158754, ...,  0.85792158,
         0.58973676,  2.8575221 ]])

In [27]:
### model training
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()

In [28]:
logistic.fit(x_train,y_train)
y_pred=logistic.predict(x_test)
print(y_pred)

[0 0 1 0 0 0 1 0 1 1 1 1 0 0 0 0 1 1 0 1 1 0 0 0 0 1 1 0 1 1 1 0 1 0 1 1 0
 0 0 0 1 0 0 0 1 0 0 1 0 0 1 1 0 1 1 0 0 1 0 0 0 0 1 1 0 0 1 0 0 1 1 1 0 1
 0 0 0 0 0 0 0 1 1 0 0 1 1 0 1 0 1 0 0 1 0 0 0 0 0 1 1 1 0 0 1 0 1 0 1 1 1
 0 0 0 0 0 1 0 0 1 0 1 0 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 0 1 1 0 0 1 0 0 1 0
 0 0 0 0 1 1 1 0 1 0 1 1 1 0 0 1 1 1 0 1 0 0 0 0 1 0 0 0 1 1 1 0 0 1 1 1 0
 0 0 0 1 1 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 1 1 1 0 1 0 1 0 0 1 1 1 0 1 1 0 0
 0 0 1 1 0 1 0 1 0 1 0 0 0 0 0 0 0 1 0 1 1 0 0 1 0 1 0 0 1 1 1 1 1 0 0 1 1
 1 0 1 1 1 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 1 1 0 1 1 1 1 0 0 1 0 0 1 0 0 0 1
 0 1 1 0]

In [29]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

In [30]:
score=accuracy_score(y_test,y_pred)
matrix=confusion_matrix(y_test,y_pred)
classification=classification_report(y_test,y_pred)
print(score)
print(matrix)
print(classification)

0.9466666666666667
[[149   4]
 [ 12 135]]
              precision    recall  f1-score   support

           0       0.93      0.97      0.95       153
           1       0.97      0.92      0.94       147

    accuracy                           0.95       300
   macro avg       0.95      0.95      0.95       300
weighted avg       0.95      0.95      0.95       300